language: node_js

node_js:
  - 10

services:
  - mongodb

before_install:
  - sleep 15
  - mongo tf2frags --eval 'db.apiKeys.insert({name:"test", key:"test"})'

install:
  - npm install

script:
  - npm run lint
  - npm test

after_success:
  - cat ./coverage/lcov.info | coveralls